### ISSUE TITLE
[general discussion] Why does numworkers x numwatchers != messages in flight?

### ISSUE THREAD

**Issue by jakepruitt** [mapbox/ecs-watchbot#103]
A common question that comes up with ecs-watchbot users is "What's up with my jobs - I specified 6 watchers with 100 workers a piece but I'm only seeing 134 jobs in flight right now?" The answer to this question usually has to do with resource availability on the cluster - there isn't anywhere to place the workers and the watchers are therefore not grabbing any more messages from the queue.

### What can we do now to help this?

At the moment, clusters scale up when there are failed task placements, but this scaling works very slowly. From what we've seen in our stacks, clusters will need to react much faster to failed task placements than they do now. Increasing the sensitivity might require a separate ticket for fixing and tracking and closing apart from this general ticket.

### What happens in the future when we remove resource polling?

The work in https://github.com/mapbox/ecs-watchbot/pull/101 removes the resource polling that's currently responsible for learning that a cluster is full and reducing the number of messages in flight. Without this logic, the only way to know a cluster is full is if the `RunTask` request fails. In #101's implementation, the watcher would retry the `RunTask` request indefinitely until some resources freed up and the task could be placed. Leaving a watcher in a potentially infinite loop could be hazardous if the job has a short timeout and gets trapped in the `RunTask` retries for the entire duration of its available time.

If we add a max number of `RunTask` retries, we would escape the infinite loop, but messages could potentially be sent back to the queue without ever reaching a worker. `NumRetries` would then be lying for that message, which wasn't exactly tried, and shouldn't be penalized for coming to a watcher while the cluster was full.

@rclark has thoughts on externalizing state of `NumRetries` of messages to some other place than the internals of the watcher or properties of the SQS messages, but they require a rather large lift. Would it be fine to leave in the infinite loop, and somehow only start the timeout counter after the message got to the worker? Is that even possible?

cc/ @emilymdubois @emilymcafee @jacquestardie @mapsam @GretaCB if you have any thoughts on how you'd want this system to work in the event of a full cluster. Ideally, would you want watchbot to do everything in its power to work up to full concurrency? Or would you want to be notified about the watchbot stack running on a full cluster, and then take manual action on scaling the cluster?

**Comment by rclark** [comment]
I think that there are three actionable issues to break out here:

- Write a function to determine exactly how many tasks could currently be placed on a cluster. This has to look at each EC2, and determine how many tasks could be placed on it, then move on to the next ec2. As an `npm run` kind of script, this can help watchbot users answer their own questions about concurrency.

- Write a better NumRetries implementation, which somehow only increments when the SQS message actually gets run by a worker.

- Alongside the removal of resource polling, place a max time that an SQS message is allowed to hang out in the failed task placement loop. If we can really nail a good NumRetries alternative, we can remove this holding pattern entirely.

I think that any other actions are actually on the EC2 / Cluster management side of things.

**Comment by rclark** [comment]
Closing -- we've got actionable tickets for everything we brought up here

**Comment by jakepruitt** [comment]
Reopening -- we're still seeing this issue come up in unpacker production, where there's enough capacity in the cluster, and plenty of messages in the queue, but watchbot isn't scaling up to full concurrency. Unclear yet where the failure is happening, since it looks like several minutes go by with the watcher hanging at less-than-maximum concurrency, enough time for the watcher to grab more messages from the queue.

Will update this ticket when next actions and reproducible test cases become apparent.

**Comment by rclark** [comment]
Stale!
