### ISSUE TITLE
Create script for checking available capacity for new workers on a given cluster

### ISSUE THREAD

**Issue by jakepruitt** [mapbox/ecs-watchbot#105]
From #103:

> Write a function to determine exactly how many tasks could currently be placed on a cluster. This has to look at each EC2, and determine how many tasks could be placed on it, then move on to the next ec2. As an npm run kind of script, this can help watchbot users answer their own questions about concurrency.

I imagine this script would live in the ecs-watchbot repo and take a parameter for the stackname of the ecs-watchbot stack and the stackname of the cluster.

cc/ @rclark @emilymdubois

**Comment by rclark** [comment]
I think the cluster's ARN could be deduced from the stack's template.

**Comment by jakepruitt** [comment]
@rclark so you would need to run this from the folder of the ecs-watchbot stack you're interested in?

**Comment by rclark** [comment]
That or make a CloudFormation [GetTemplate API call](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CloudFormation.html#getTemplate-property).

**Comment by emilymdubois** [comment]
Closed by https://github.com/mapbox/ecs-watchbot/pull/110
