### ISSUE TITLE
Place a max time an SQS message is held in failed RunTask loop

### ISSUE THREAD

**Issue by jakepruitt** [mapbox/ecs-watchbot#107]
From #103:

> Alongside the removal of resource polling, place a max time that an SQS message is allowed to hang out in the failed task placement loop. If we can really nail a good NumRetries alternative, we can remove this holding pattern entirely.

The motivation here is that some SQS messages have a timeout that should not be affected by the cluster's resource availability.

cc/ @emilymdubois @rclark

**Comment by rclark** [comment]
I believe this loop was removed, right?

**Comment by jakepruitt** [comment]
Yep, opting for just one and done.
