### ISSUE TITLE
Additional metrics to mine from cloudwatch logs

### ISSUE THREAD

**Issue by rclark** [mapbox/ecs-watchbot#112]
- Work message ApproximateReceivesCount (important for proposal in #106)
- Worker duration
- Watcher concurrency

cc @jakepruitt @emilymdubois

**Comment by jakepruitt** [comment]
> Watcher concurrency

Is this something that we should start logging? Or is this a metric we can collect from the `RunningCount` of the watcher service?

I personally would like a metric of Worker concurrency, both max concurrency and number of workers running. I think these can be extracted from the logs with a little extra logging. `ApproximateMessagesNotVisible` is a decent proxy, but can sometimes get out of sync, like during a deploy.

> Work message ApproximateReceivesCount

Would we log this from within the worker or within the watcher?

**Comment by rclark** [comment]
[These logs](https://github.com/mapbox/ecs-watchbot/blob/8f3da4fa370df7f10b62336502be5eb516f646b1/lib/main.js#L52-L57) provide minutely insight into the number of workers that the watcher is currently tracking

```
concurrency ${configured max concurrency} | tasks ${currently tracking}
```

The ApproximateReceiveCount [could be logged from the watcher here](https://github.com/mapbox/ecs-watchbot/blob/8f3da4fa370df7f10b62336502be5eb516f646b1/lib/main.js#L150)

```
log.info('[%s] started task for attempt %s on %s: %s', ...
```
