### ISSUE TITLE
Ignore CannotStartContainerError errors

### ISSUE THREAD

**Issue by rclark** [mapbox/ecs-watchbot#121]
Let's ignore these types of errors, and simply return the message to the queue for another retry.

cc @jakepruitt

**Comment by mapsam** [comment]
Would it be worth adding this as a parameter? Or are you thinking _always_ ignore?

**Comment by rclark** [comment]
Always. This isn't worth a configuration parameter because you'll still alarm on error rate if there's a serious problem.
