### ISSUE TITLE
Adjust log groups, stream names

### ISSUE THREAD

**Issue by rclark** [mapbox/ecs-watchbot#128]
We want to get gitsha's out of our log group names, so that log groups persist between deploys. Will still want the gitsha involved in the mix, so later on we can deduce what version any set of logs came from.

1. [Remove the serviceVersion](https://github.com/mapbox/ecs-watchbot/blob/3b024444400667f6da4c5219de4dfa302bd96681/lib/template.js#L733) from the log group's name.

2. [Change the stream prefix](https://github.com/mapbox/ecs-watchbot/blob/3b024444400667f6da4c5219de4dfa302bd96681/lib/template.js#L592) so that it includes the gitsha.

cc @mapsam @yhahn

**Comment by GretaCB** [comment]
Happy to lend a hand here, esp as I learn more about metric-ifying

**Comment by mapsam** [comment]
@rclark do we need to also remove the `options.serviceVersion` from the [LogGroupName of the Logs::LogGroup](https://github.com/mapbox/ecs-watchbot/blob/3b024444400667f6da4c5219de4dfa302bd96681/lib/template.js#L188)?

**Comment by rclark** [comment]
Yes! In fact, [here were I originally linked](https://github.com/mapbox/ecs-watchbot/blob/3b024444400667f6da4c5219de4dfa302bd96681/lib/template.js#L733) we should probably be using a `cf.ref` or `cf.getAtt` to grab the log group's name instead of repeating the same thing twice.

**Comment by mapsam** [comment]
> using a cf.ref 

Good idea, on it.

Seeing `awslogs-stream-prefix` in two places as well, for the [worker](https://github.com/mapbox/ecs-watchbot/blob/3b024444400667f6da4c5219de4dfa302bd96681/lib/template.js#L592) and [watcher](https://github.com/mapbox/ecs-watchbot/blob/3b024444400667f6da4c5219de4dfa302bd96681/lib/template.js#L641). Same thing?

**Comment by rclark** [comment]
Yes please!

**Comment by mapsam** [comment]
@rclark can this be closed now that #129 has been merged?
