### ISSUE TITLE
`ReceiptHandle is invalid` error messages

### ISSUE THREAD

**Issue by batpad** [mapbox/ecs-watchbot#135]
We are seeing errors like this in the `osm-adiff-watchbot` stack:

```
[Wed, 08 Mar 2017 11:56:00 GMT] [watchbot] Error in tasks: Value AQEB1r2G1xUgtM7qqQ38i3rHkee4yvzg3Jo0X5ukMCn8BTGVkR2KU4IWCFHDGJl1s8knq7FLRDjcPPLP8mTPLXCuHQRft8JdUPDeVL/RRsSgIrm/V5ILM6niJxBXzeJUKgdUhsjNldstmXQuipqFfTWU0BNNro+A/mLiSEGmjzJou1TQXaR3VQMwjMxJ60FQA0xFNSEGm72dhOA9YpTdT7ZJTAVW+oiSD1x4560TJE81NPdADzT+ZE0rWhonp0u+qxxBvGHem1VR09i5xGUHXcobUEYBUmTKAHRWR3xmLReDbSUvfnCdFe/d3iak/4e+6gdiK/jLjtj0VhwvtwX0hzsPph1SVJLDWom9Y4UsLul/T4vAWtWyH2kz2+EDaBMCCq85PZbytQ9l1gYiRK8PveuZV6Ce7TTuzVGuY9Wkr6HNGhxuI3IWttNge3/V1KrLCYyL for parameter ReceiptHandle is invalid. Reason: Message does not exist or is not available for visibility timeout change.
```

Just wondering what exactly this means and if this is something we should be worried about.

cc @rclark @geohacker  . thank you.

**Comment by rclark** [comment]
The ReceiptHandle is what the watcher container uses to either remove a message from SQS (if processing was a success), or return it (if it needs a retry). The handle is provided to the watcher when it receives a message from SQS. If the message gets received again before that first one gets returned, then the handle from the first receive becomes invalid.

My guess as to why this might've happened is that your `messageTimeout` values are not quite tuned right, and a message got received a 2nd time before the first one finished. When the first one *did* finish, it tried to delete/return the message but has an invalid handle at this point.

**Comment by batpad** [comment]
Thanks for the explanation, @rclark . Closing here.
