### ISSUE TITLE
Undeleted messages

### ISSUE THREAD

**Issue by uvollmer** [mapbox/ecs-watchbot#143]
I have been seeing weird thing with messages using ECS. This is not happening a lot but worth documenting here:

- Worker starts with message at `t1`

 `{"subject":"stuff", "message":"{}", "receives": "1"}`

- Worker process the job successfully and logs

`{"outcome":"success", "reason":"success", "duration":"100"}`

- Somehow the message stays inflight the queue 
- At `t1 + messageTimeout`, a new worker starts with the same message

 `{"subject":"stuff", "message":"{}", "receives": "2"}`

This must be an issue with the message deletion when a job has been processed.

It is not a big issue for most of the use cases since this means that a job could get processed two times. 
However, this can be an issue when using [watchbot-progress](https://github.com/mapbox/watchbot-progress) with a stack using something like
[this example](https://github.com/mapbox/watchbot-progress/blob/master/examples.md#bash). In this case, if the second receives happen once all the part have already been processed, it will re queue the reduce job and can screw everything downstream.

cc @rclark

**Comment by rclark** [comment]
The most common reason this occurs is if the worker's `messageTimeout` setting is less than the time it actually takes for the worker to process a message. Say the `messageTimeout` is 3 seconds. An SQS message is pulled from the queue and watchbot launches worker A to start processing, but it takes 5 seconds to finish the work. 3 seconds later, worker A is still working but the timeout has elapsed, so the message becomes visible in SQS again. Worker B gets launched to process the task, and now you're duplicating work. 

In the context of watchbot-progress there are two tools to help now:

1. When processing a `map` phase job, first call `progress.status(jobid, partnumber)`. The response will tell you if this part has already been completed.

2. When processing a `reduce` phase job, first call `progress.status()`. Look for `reduceSent: true` in the payload. This would indicate a repeat attempt at the `reduce` job. This does require that somewhere in the processing of the `reduce` job, you called `progress.reduceSent(jobid)` to indicate that you've started (or finished) a reduce job.

**Comment by uvollmer** [comment]
@rclark thanks for you helpful answer!

I just want to state that I am sure the stack had a much bigger `messageTimeout` than it took to process the job, so not sure what happened and if it came from AWS failures.

**Comment by rclark** [comment]
It is also possible for SQS to allow for the delivery of a message more than once. They guarantee the messages will be delivered _at least once_, but not _exactly once_. 

Do the additional progress functions help in the way you need? If so, please feel free to close the issue.
