### ISSUE TITLE
Missing 'link' on how to create cloud formation stack

### ISSUE THREAD

**Issue by imkheong** [mapbox/ecs-watchbot#144]
First of all, thank you for sharing the work on Github, it is definitely a good effort.

I have been going through the code for a while now, trying to wrap my head around the concepts. I do appreciate the fact that the architecture provides a scalable architecture handle batch processing tasks.

With hours spent on reading through the documentation and poking around, I am unable to figure out how to get started. :(

From [1 Building a Watchbot template](https://github.com/mapbox/ecs-watchbot/blob/master/docs/building-a-template.md), it suggests that we should use Node.js to write a javascript file to create the cloud formation template required. 

The missing link to me is that I am not sure what to do with it. Am I to use Node.js AWS SDK to create a cloud formation stack? Or is it to write out the template to some file to be uploaded to AWS Cloud Formation?

I need some help here.

Also if you guys can create an end-to-end tutorial for that, that will be really helpful too. :)

Thanks in advanced.

**Comment by rclark** [comment]
I think that the missing link you're looking for is this last bullet in the markdown doc you referenced:

```
- use cfn-config to deploy the template by referencing the script that you've written.
```

Check out https://github.com/mapbox/cfn-config. This is a command-line utility that will parse the JS file and help you deploy it using AWS CloudFormation.

Another option is to use https://github.com/mapbox/cloudfriend. This library includes a CLI utility that you can access if you have globally linked the cloudfriend repo (e.g. `npm install -g @mapbox/cloudfriend`). 

```
build-template /path/to/your/template.js > ~/tmp/cloudformation-template.json
```

Then you can take this JSON file and deploy it using the web console for CloudFormation, or any other AWS SDK that you'd like to use.

Let me know if this helps!
