### ISSUE TITLE
messageTimeout default to max value

### ISSUE THREAD

**Issue by rclark** [mapbox/ecs-watchbot#145]
`messageTimeout` is an important, but often overlooked parameter. Currently, its default setting is an arbitrarily chosen value (10 minutes). If jobs take longer to process than 10 minutes, and the caller hasn't learned about `messageTimeout` yet, they get pretty confusing results where jobs are processed more than once.

Instead of this arbitrary 10 min timeout, the default value should be the maximum possible from SQS.

**Comment by brendanmcfarland** [comment]
In watchbot 4 `messageTimeout` is now defaulted to 3 minutes. `message.heartbeat` will keep refreshing the visibility timeout, and `maxJobDuration` is available as a parameter for limiting how long a message will be processed before the child_process is killed and the message is retried. see #203 & #230
