### ISSUE TITLE
Describe the importance of ECS_ENGINE_TASK_CLEANUP_WAIT_DURATION

### ISSUE THREAD

**Issue by rclark** [mapbox/ecs-watchbot#15]
If this [ecs-agent configuration parameter](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-agent-config.html) is not set lower than the default value of 1h, and your watcher is doing lots of rapid work, you're going to have a bad time.

Readme should mention this as a caveat, and also probably have a clear section on expected cluster configuration and settings.

**Comment by jakepruitt** [comment]
Since watchbot 4 no longer relies on rapidly starting and stopping ECS tasks, I think we can remove this issue.
