### ISSUE TITLE
Make the failed worker placement alarm customizable

### ISSUE THREAD

**Issue by nickcordella** [mapbox/ecs-watchbot#169]
Would it be possible to make the `failedWorkerPlacementAlarm` more customizable by accepting optional parameters for [some of the properties](https://github.com/mapbox/ecs-watchbot/blob/master/lib/template.js#L301-L303), as is done with the [queue size alarm](https://github.com/mapbox/ecs-watchbot/blob/master/lib/template.js#L406-L407), for instance?

This is handy if one is causing regular, periodic, large cluster scale-ups that cause transient spikes in the failed placements. I am happy to take a crack at a PR. I'd probably make the `EvaluationPeriods` an option, and maybe the `Threshold` too.

cc @rclark

**Comment by rclark** [comment]
Sounds good @nickcordella

**Comment by oini** [comment]
Implemented in PR #170
