### ISSUE TITLE
Resource polling issues during deploys

### ISSUE THREAD

**Issue by rclark** [mapbox/ecs-watchbot#17]
```
Error polling cluster resources: Container instance cannot be empty.
```

This seems to happen once as soon as the watcher starts up.

**Comment by rclark** [comment]
I've seen this happening now at other times than just at watcher startup.

**Comment by emilymdubois** [comment]
@rclark I can only recreate the watcher startup scenario, but it looks like this error is thrown when the [instances array in the `resources.available`](https://github.com/mapbox/ecs-watchbot/blob/de041ebd8d91230fa51cde194ffaf27188580175/lib/resources.js#L46) is empty, which causes the [`describeContainerInstances` function](https://github.com/mapbox/ecs-watchbot/blob/de041ebd8d91230fa51cde194ffaf27188580175/lib/resources.js#L48) to return a native AWS error.

A few questions here:

1. Is it expected that we don't have any registered instances during watcher startup?
2. If so, perhaps we can return a custom message in the event of ^^ and bypass [the describeContainerInstances call](https://github.com/mapbox/ecs-watchbot/blob/41ef6c9d4210ad7e7df0f9587ef31508de42c57f/lib/resources.js#L46-L68)?
3. Is this a scenario that we would want to handle differently during watcher startup vs. other times (i.e., maybe this is expected during startup, but not expected at other times)?

**Comment by rclark** [comment]
> Is it expected that we don't have any registered instances during watcher startup?

Not really... because the watcher container that is making a request runs on a cluster that has to have container instances -- otherwise the watcher wouldn't have a place to run. However we do see it consistently on startup, so something systematic is at play here.

Is it possible that there's a container/permissions race-condition here? That the container launches before it has permission to ListContainerInstances?

> perhaps we can return a custom message in the event of ^^ and bypass the describeContainerInstances call?

Yeah we definitely can but... 

> Is this a scenario that we would want to handle differently during watcher startup vs. other times 

Yes. If this were happening consistently at times other than startup it would be a) confusing and b) probably indicate some AWS issue with the ECS API.

**Comment by emilymdubois** [comment]
Closed via https://github.com/mapbox/ecs-watchbot/pull/67#issuecomment-256182416
