### ISSUE TITLE
Defaults override 0s on options

### ISSUE THREAD

**Issue by arunasank** [mapbox/ecs-watchbot#171]
For example on https://github.com/mapbox/ecs-watchbot/blob/master/lib/template.js#L149-L150,  when I set `options.errorThreshold = 0`, to trigger an alarm on any error, the value set by me gets overriden to the default value of 40, because `0 => false` in JavaScript.

cc/ @rclark

**Comment by jakepruitt** [comment]
@arunasank do we know if this is still a problem with watchbot 4?

**Comment by arunasank** [comment]
This is no longer an issue in watchbot 4, since we are explicitly setting the errorThreshold defaults as part of https://github.com/mapbox/ecs-watchbot/blob/master/lib/template.js#L111-L133.
