### ISSUE TITLE
[cli] worker-capacity command fails for custom-named watchbot resources

### ISSUE THREAD

**Issue by rclark** [mapbox/ecs-watchbot#179]
https://github.com/mapbox/ecs-watchbot/blob/d1dda99b07736431365bdc58116374206cbd0687/lib/worker-capacity.js#L54

This line of code assumes that the worker's task definition uses the default prefix/name `WatchbotWorker`. Stacks with multiple watchbots usually provide custom prefixes which create custom-named task definitions.

To guard against this, the `worker-capacity` command needs to be more intelligent about identifying watchbot task definitions. It should adopt a process [similar to the `dead-letter` command](https://github.com/mapbox/ecs-watchbot/blob/d1dda99b07736431365bdc58116374206cbd0687/lib/dead-letter.js), where we find all the task definitions that were generated by `watchbot.template()`, regardless of prefix, and then prompt the user to select the one that they're interested in.

cc @dputtick

**Comment by jakepruitt** [comment]
`worker-capacity` has been deprecated.
