### ISSUE TITLE
NotifyAfterRetries

### ISSUE THREAD

**Issue by rclark** [mapbox/ecs-watchbot#2]
Add a parameter that allows the stack to configure a number of attempts that should be made to process any single message before sending a failure notification.

**Comment by mapsam** [comment]
Should this have a default value? If so, what should that default be?

**Comment by rclark** [comment]
Default should be to notify after the very first failure.

**Comment by mapsam** [comment]
Default `0` it is!

**Comment by mapsam** [comment]
Resolved in #68!
