### ISSUE TITLE
Logging in Watchbot4

### ISSUE THREAD

**Issue by tapasweni-pathak** [mapbox/ecs-watchbot#204]
### Generic TODO

- deciding on `FilterPattern` for correctly parsing logs for `MetricNamespace: 'Mapbox/ecs-watchbot'`, custom CloudWatch metrics
- logging corrections/enhacements
- any other logging which needs to be added
- What all `MetricNamespace: 'Mapbox/ecs-watchbot'`, CloudWatch metrics should be added to Watchbot4, `master` has
    - WorkerErrorMetric (has an alarm as WorkerErrorsAlarm)
    - WorkerDurationMetric
    - WorkerPendingMetric
    - WatcherConcurrencyMetric
    - FailedWorkerPlacementMetric (has an alarm as FailedWorkerPlacementAlarm) 

### Watchbot Master branch (current version)

For WorkerErrorMetric and FailedWorkerPlacementMetric, we have setup logging as
https://github.com/mapbox/ecs-watchbot/blob/master/lib/tasks.js#L99-L102

```js
tasks.report = function(outcome) {
  switch(outcome) {
    case tasks.outcome.success: return 'success';
    case tasks.outcome.noop: return 'no-op, will retry';
    case tasks.outcome.fail: return 'failed, removed from queue';
    case tasks.outcome.retry: return 'failed, will retry';
  }
};
```

and

```js
log.warn(
    '[%s] %s',
    env.MessageId,
    JSON.stringify({
        failedPlacement: 'true',
         reason: err.message
    })
);
```

The `FilterPattern` we set is

-  `{ $.outcome = "failed*" }` on [WorkerErrorsMetric](https://github.com/mapbox/ecs-watchbot/blob/master/lib/template.js#L316-L327)
-  `'{ $.failedPlacement = true }'`  on [FailedWorkerPlacementMetric](https://github.com/mapbox/ecs-watchbot/blob/master/lib/template.js#L288-L299).
- `'{ $.duration = * }',` on [WorkerDurationMetric](https://github.com/mapbox/ecs-watchbot/blob/master/lib/template.js#L344-L357)
- `'{ $.pending = * }',` on [WorkerPendingMetric](https://github.com/mapbox/ecs-watchbot/blob/master/lib/template.js#L359-L372)

In the watchbot master branch, we are able to have datapoints on custom metrics as we log this way.

### Watchbot 4(Watchbot container-recycling branch)
1. None of the above filter pattens would work as currently the logging setup is different.
2. logs prefixed with `[watcher]` : [ref](https://github.com/mapbox/ecs-watchbot/blob/container-recycling/lib/worker.js#L32), where they could be `[worker]` : [ref](https://github.com/mapbox/ecs-watchbot/blob/master/lib/tasks.js#L99-L102)
3. logs prefixed with `[failure]` has no special object like previous version, they would output something like, [ref](https://github.com/mapbox/ecs-watchbot/blob/container-recycling/lib/logger.js#L34).
```json
    [watcher] [<id>] [failure]
    {
        "code": 255,
        "signal": null,
        "duration": 7
    }
```
4.  A worker failing would log as
  -  `[error] [worker] ${err.message}`
  -  `[failure] ${JSON.stringify(results)}`

5. Queue error would log as 
  -  `[error] [sqs] ${err.message}`

6. Duration would be logged through [ref](https://github.com/mapbox/ecs-watchbot/blob/container-recycling/lib/worker.js#L15-L20)
```js
     const duration = Date.now() - start;
     resolve({ code, signal, duration });
  });
    
   child.stdout.pipe(logger.stream());
   child.stderr.pipe(logger.stream());

```

### Questions/Next steps
I’m thinking of

- WorkerErrors would be filtered with a metricFilter on `[error] [worker]`
- QueueError metric filtered on `[error] [sqs]`
- Duration metric filtered on `duration` value of object logged.
- Failed worker metric filtered on `[failure]`
- FailerWorkerPlacementMetric logs currently are only in service history.
- Create an object like `outcome` while logging in current version so that the logs can be correctly parsed with `{ $.outcome = "failed*" }` otherwise with container-recycling branch the metric filter would be set to `"[failure]"`.

Other than this I would enhance the logs to put `[worker]` , `[watcher]` when they are worker or watcher logs, which would then be added in `MetricFilter` value.

To make the logs parsable and parse them correctly for custom namespace CloudWatch metric does this cleanup/enhancement and filtering of logging looks good? Is there any other metric or logging prefixing or logging messages needs to be added which I'm missing here?

cc @rclark @mapbox/platform-engine-room.

**Comment by jakepruitt** [comment]
Thanks for cutting this @tapasweni-pathak! Great code references.

I think most of the recommendations look great. I'd adjust just a few of them:

> Other than this I would enhance the logs to put [worker] , [watcher] when they are worker or watcher logs, which would then be added in MetricFilter value.

I think any logs that watchbot is doing should be prefixed with `[watcher]` logs, while the `[worker]` logs should be reserved explicitly for anything that runs inside of the worker sub-process. That way, watchbot users know the difference between the logs that they write in their application (`[worker]`) and the logs that are written by the watchbot code (`[watcher]`).

> Create an object like outcome while logging in current version so that the logs can be correctly parsed with { $.outcome = "failed*" } otherwise with container-recycling branch the metric filter would be set to "[failure]".

I think we can now change this to use the `code` property to determine the `outcome`. Are `outcome: failure` and `[failure]` equivalent in the new version? Are `outcome: failure` and `code != 0` equivalent?

> WorkerErrors would be filtered with a metricFilter on [error] [worker]

Are the `WorkerErrors` here errors that take place inside of the worker subprocess? Are they errors that take place inside of `./lib/worker.js`?

**Comment by tapasweni-pathak** [comment]
This discussion is moved to the PR. Just as an update here, going ahead with `[watchbot]` at few places and `[worker]` only in child.process logging. `workerError`, `workerFailure` will have `[watchbot]` in their logs.

> > Create an object like outcome while logging in current version so that the logs can be correctly parsed with { $.outcome = "failed*" } otherwise with container-recycling branch the metric filter would be set to "[failure]".

> I think we can now change this to use the code property to determine the outcome. Are outcome: failure and [failure] equivalent in the new version? Are outcome: failure and code != 0 equivalent?

https://github.com/mapbox/ecs-watchbot/blob/50d0c22a6218997026a79c5f9288035b5e17a18d/lib/worker.js#L64-L67

There are different codes which are returned 0, 3, 4. So the outcome:failure and code !=0 aren't the same. I'll try to add `filterpattern` check for specific code.

> > WorkerErrors would be filtered with a metricFilter on [error] [worker]

> Are the WorkerErrors here errors that take place inside of the worker subprocess? Are they errors that take place inside of ./lib/worker.js?

They are termed as `workerErrors` and are inside the `lib/worker.js`. The child process logs with a logger.stream.
