### ISSUE TITLE
Metrics dashboard in watchbot 4

### ISSUE THREAD

**Issue by jakepruitt** [mapbox/ecs-watchbot#216]
We should create a dashboard in the cloudformation template for watchbot stacks that comes with a few graphs:

- CPUUtilization and MemoryUtilization
- DesiredCapacity and RunningCapacity
- ApproximateMessagesNotVisible and ApproximateMessagesVisible
- NumberOfMessagesDeleted
- Is there a logs widget? Or anything we'd want to put in a text widget?

cc/ @mapbox/platform

**Comment by arunasank** [comment]
> * Is there a logs widget? Or anything we'd want to put in a text widget?

There is no logs widget. The text-widget is if we wanted to add something in markdown, which we don't really need. First draft of the dashboard is up!
