### ISSUE TITLE
Discussion: Is "fresh: true" the right name?

### ISSUE THREAD

**Issue by jakepruitt** [mapbox/ecs-watchbot#217]
Per conversation, we should re-assess the naming of fresh mode since it doesn't get to the heart of the difference from a user's perspective. From a user's perspective, the default mode restricts writes to only volumes and the "fresh" mode allows users to write anywhere on the filesystem with a significant performance penalty.

With that in mind, should we rename `fresh` mode to one of these:

- `unrestricted`
- `sudo`
- `slow`
- `write_anywhere`

cc/ @mapbox/platform-engine-room @emilymcafee @rclark for more ideas.

**Comment by rclark** [comment]
I have been feeling like a good option to consider would be to bust fresh mode apart into 2 different configuration options:

- **sudo: true/false**: (default false) whether or not the child process runs as root
- **maxMessagesPerContainer: Number**: (default infinity) how many messages a container is allowed to process before shutting itself down. This might default to infinity if `sudo: false` and default to 1 if `sudo: true`.

**Comment by jakepruitt** [comment]
> maxMessagesPerContainer

Initially reading this name, I thought it was describing the number of parallel messages being processed at once in a container. I like the idea of using this option as a way to ensure filesystems don't grow too large, while potentially giving developers the option to re-use files. I think we should probably keep planning around those options to the https://github.com/mapbox/ecs-watchbot/issues/210 ticket.

> sudo

Since we no longer rely on a non-sudo user to restrict file system writes, I don't think we should go with `sudo`. Instead, should we go with the `readOnlyFilesystem` option, and have that be default to `true`? It feels strange to opt into something by saying `false` tho 😕.

Maybe we could go with `writableFilesystem: true`?

**Comment by arunasank** [comment]
> Maybe we could go with writableFilesystem: true?

👍 to this. I think the `maxMessagesPerContainer` is something we can work towards, since we haven't yet engineered for an option like `maxMessagesPerContainer: 10` (Our current system works for `maxMessagesPerContainer: 1` and `maxMessagesPerContainer: <infinity>`), and settle with replacing `fresh: true` to `writableFileSystem: true` for the time being.
