### ISSUE TITLE
Allow Ref type for `maxSize` cloudformation option

### ISSUE THREAD

**Issue by jakepruitt** [mapbox/ecs-watchbot#241]
Since the [scaling adjustment for the watchbot service is calculated by dividing the `maxSize` by 10](https://github.com/mapbox/ecs-watchbot/blob/master/lib/template.js#L470), users have to use a hard-coded value for the `maxSize` option. This hard-coded value causes friction for watchbot users since they will likely want to have different size configurations for different environments.

### Potential paths forward

I'm not sure how we're going to figure this one out. Here are some ideas:

- Let people determine the scaling step as a parameter, rather than a mathematically derived value? Set the default to something we know the cluster can handle, like 5 or 10? The danger here is that we could wind up in a place where people hack through and set ridiculously high scaling adjustments 😕 
- Use some secret hidden autoscaling feature I don't know about to do percentage-based scaling up to the max?
- I can't find any way to do math or inequalities in cloudformation, so I think that's out of the question, though I'm willing to be wrong if someone else [wants to take a look](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-conditions.html).

cc/ @mapbox/platform-engine-room

**Comment by rclark** [comment]
> do percentage-based scaling up 

Shouldn't we be able to do this? From https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-applicationautoscaling-scalingpolicy-stepscalingpolicyconfiguration-stepadjustment.html

> ScalingAdjustment
>
> The amount by which to scale. The adjustment is based on the value that you specified in the AdjustmentType property (**either an absolute number or a percentage**). A positive value adds to the current capacity and a negative number subtracts from the current capacity.

**Comment by brendanmcfarland** [comment]
One downside of the percentage-based scaling is that I'm pretty certain it's based solely on the current capacity of the target. So as a general rule scaling will be slow at the lower end and much larger at the top end. Not always ideal.

We can mitigate a bit with [MinAdjustmentMagnitude](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-policy.html), to make the early steps have a default floor.

Thinking 

- AdjustmentType: PercentChangeInCapacity
- MinAdjustmentMagnitude: 10
- StepAdjustments: 50 

Should result in adding the greater of 10 tasks or 50% of the current capacity.

I'd vote for exposing both the percentage based scaling amount and minimum scaling step to developers if they want to adjust; but not making them required.

**Comment by brendanmcfarland** [comment]
>  I would vote the opposite -- scaling rate is a serious issue for the teams that maintain compute, but if you ask a developer how fast they want to scale, the answer will always be "as fast as possible". Since the question has no meaningful answer from the dev's perspective, and slowing down scaling is only really helpful for those managing clusters, why should the dev be allowed to adjust it? Instead, shouldn't it be something that the cluster-managers can do their best to allow it to be as fast as possible and still safe?

I'd make arguments that sometimes `as fast as possible` is a valid answer; but you're 100% right that walling off scaling mitigates the ability for a developer to shoot our compute in the foot with `as fast as possible` scaling rules. Plus; using a custom resource to `patch other gaps in the scaling logic` gives a flexible fix to other scaling troubles we may encounter. 

I started on a custom resource in #249 which should unlock maxSize as a cloudformation parameter while maintaining the 10% scaling linear scale up with a cap of 100 tasks per adjustment.

**Comment by brendanmcfarland** [comment]
Closed with #249, next up some docs to close out #242
