### ISSUE TITLE
watchbot service churns tasks when initially receiving messages

### ISSUE THREAD

**Issue by brendanmcfarland** [mapbox/ecs-watchbot#261]
We've observed some adverse scaling behavior on stacks where the minSize is 0.  It seems to be worse in stacks that process just one message, or stacks that empty their queue in one metric period. It's also not necessarily limited to stacks with minSize 0; but the simplest example of the conflicting scaling is a stack with minSize zero.

From what I can tell this is the general idea of what's happening. A picture would help here; but posting the prose for now.

#### A - 21:00 UTC | 0 Running Tasks | 0 Message Visible | 0 Messages Not Visible
- Scaledown - Active
- Scaleup - InActive

This is the steady state of a queue or service with no messages and min size zero.

_21:01 UTC - put a message in the queue_

#### B - 21:05 UTC | 0 Running Tasks | 1 Message Visible | 0 Messages Not Visible**
- Scaledown - Active
- Scaleup - Active

#### C - 21:06 UTC | 1 Running Tasks | 1 Message Visible | 0 Messages Not Visible**
- Scaledown - Active
- Scaleup - Active

At this point Scale Down and Scale up fight or the next five minutes as the two scaling rules scale the service up and down. Tasks are started and stopped during this period. Messages are received and then they timeout as the task is stopped without exiting. This is the adverse scaling behavior.

At 21:10 UTC  the state is either:

**D: 21:10 UTC | 1 Running Tasks | 0 Message Visible | 1 Messages Not Visible**
Scaledown - InActive
Scaleup - InActive
  
**E: 21:10 UTC | 0 Running Tasks | 0 Message Visible | 1 Messages Not Visible**
Scaledown - InActive
Scaleup - Inactive

**F: 21:10 UTC | 0 Running Tasks | N Message Visible | 1 Messages Not Visible**
Scaledown - InActive
Scaleup - Active

**G: 21:10 UTC | 1 Running Tasks | N Message Visible | 1 Messages Not Visible**
Scaledown - InActive
Scaleup - Active

In **D or G** - then the work should continue uninterrupted and we’ve successfully gotten a task to get to work.

In **E** - then we’re headed back to the **B** state again once the message returns to visibility. I appears can go from B->E->B->E more than once.

In **F** - there are enough messages that some are visible at 21:10, the scale up will be active and the scale down will be inactive. You should expect work to start successfully without churning between scaling up and down.

I think the scale down cooldown is not preventing the scaling churn in state B; because the cooldown only prevents further changes to capacity. So autoscaling will go from 1→0 again and again within the cooldown window; but the cooldown will prevent scaling from 2→1 and 1→0 within the same time window.

This problem isn't necessarily solved by minSize > 0. A service could have a minSize of 10 and upon receiving work it will churn tasks between 10 and it's scale up increment; because both scale up and scale down will be active. The service could potentially churn all its tasks including the ones that were present before the scale up, preventing any stable work.

Next actions I see are to make sure we properly understand what's happening at the start of scale up / scale down and coming up with ways to mitigate this behavior. It's been tough to track this issue because I've also observed the same watchbot services start seamlessly without scaling churn.

cc @mapbox/platform-engine-room

**Comment by jakepruitt** [comment]
Fixed in #267
