### ISSUE TITLE
Set cli-spinner and cwlogs as normal dependencies?

### ISSUE THREAD

**Issue by ajashton** [mapbox/ecs-watchbot#274]
`cli-spinner` and `cwlogs` are set as devDependencies, but they are used by the `watchbot-dead-letter` CLI tool. Should these be normal dependencies?

**Comment by hcourt** [comment]
We keep the CLI tool runtime from muddying the docker runtime by leaving these as dev-only dependencies.  If these were normal dependencies, they would also be included on every docker install.
