### ISSUE TITLE
Track WorkerDuration, MessageReceives metric on CloudWatch

### ISSUE THREAD

**Issue by arunasank** [mapbox/ecs-watchbot#277]
We had metrics based on CloudWatch log filters earlier to track these metrics from the logs, but currently we no longer have metrics for these two values. 

Let's track these on CloudWatch: 
* WorkerDuration: Modify https://github.com/mapbox/ecs-watchbot/pull/184/files#diff-8dc0fb1119587e3ecd8cc6a9c9969d05L344
* MessageReceives: Modify https://github.com/mapbox/ecs-watchbot/pull/184/files#diff-8dc0fb1119587e3ecd8cc6a9c9969d05L374

cc/ @mapbox/platform @amishas157

**Comment by vsmart** [comment]
👍 These metrics would be super useful for ecs-conex - so @mapbox/assembly-line can grab. thanks for ticketing, aruna!

**Comment by vsmart** [comment]
👋 @amishas157 @arunasank FYI these metrics were released in watchbot `4.11.1` 🎉
