### ISSUE TITLE
Perf recording and insights into performance of watchbot workers

### ISSUE THREAD

**Issue by sgillies** [mapbox/ecs-watchbot#290]
The Imagery team is on a mission to improve our [pixelmonster's](https://github.com/mapbox/pxm) performance. We're already profiling our Python and C code, but I'm curious if there are more and deeper insights to be had by turning on the Linux instrumentation for our staging and/or production render processes. I've watched Brendan Gregg's talk on [flame graphs](http://www.brendangregg.com/flamegraphs.html) and it looks like a promising tool for analyzing the real world performance of rasterio, GDAL, and Linux. We have a little bit of prior art at Mapbox in the Mason project: https://github.com/mapbox/mason/pull/368.

I'm new to this kind of problem, especially as it applies to ECS. Does Amazon's platform already do this for us? Does the platform team already have such a tool? If not, is it feasible for watchbot to perf record a worker and then dump the recording to S3 for analysis at the end of a pxm render? If this isn't a solved problem, perhaps we could schedule a call to discuss it, yes?

cc @mapbox/platform @jacquestardie

**Comment by rclark** [comment]
I'm no expert on this either, but this would be interesting to explore. Something like:

- An additional template build option `perfOutput`. If the caller provides it, this should be an S3 folder where perf outputs could be written

- If that option is specified, the watchbot process would monitor the performance of the worker child process it launches. When that child process exits, the output is uploaded to S3. 

https://github.com/mapbox/ecs-watchbot/blob/966ca4b8213a5f5269b8c3f7a9cbcff9ae3dd1f9/lib/worker.js#L15-L22

**Comment by sgillies** [comment]
@rclark that sounds pragmatic. I think an option to specify perf-record args will be needed, too: http://man7.org/linux/man-pages/man1/perf-record.1.html. There are many, and I some exploring will be required.

The imagery team's needs for this are not immediate. Which is good, because @daniel-j-h pointed out that there are some hurdles when running perf in a Docker container. I'm hoping to learn more about those in this recorded talk: http://www.brendangregg.com/blog/2017-05-15/container-performance-analysis-dockercon-2017.html.

**Comment by rclark** [comment]
> extra capabilities need to be added to containers that are run

There is support for the `SYS_ADMIN` capability that can be added to an ECS container [cloudformation docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-kernelcapabilities.html).

> runs perf from the container host

If perf is run from the host then I'm confused -- current architecture for watchbot is: host runs a container (the watcher), container receives an SQS message, container runs a child process (worker). Copying files from the container to the host is very tractable, but how / when would we need to trigger an action at host level?

**Comment by sgillies** [comment]
@rclark that's a question I don't have a handle on yet. I'm switching my macbook for a linux laptop next week so that I can get dirty with perf. If it's okay with you, I'd like to park this discussion until November when I have more experience.

**Comment by sgillies** [comment]
Closing this. It's an interesting problem, but not presently an imagery team goal.
