### ISSUE TITLE
Duration metrics, message details

### ISSUE THREAD

**Issue by rclark** [mapbox/ecs-watchbot#3]
Watchbot could log the SQS message metrics and task duration upon completion (success or fail).

**Comment by mapsam** [comment]
@rclark does #91 close this?

**Comment by rclark** [comment]
Not really -- it would be nice if the number of receives on a message were also logged, for example.

**Comment by perrygeo** [comment]
Another related metric would be the total elapsed time from when the message hit the queue to when the task finished.

**Comment by rclark** [comment]
This will be fixed when we solve #112
