### ISSUE TITLE
No Container Instances were found in your cluster.

### ISSUE THREAD

**Issue by hypertd** [mapbox/ecs-watchbot#302]
Currently we have managed deploy a CloudFormation stack using watchbot and cnf-config and have the image housed in ECR however were currently blocked by another error.

The watchbot service event is reporting that `"No Container Instances were found in your cluster."` on AWS.

Wondering if someone is able to help with this?

**Comment by hypertd** [comment]
Hopefully this helps someone. This error can happen when you run your generated Cloudformation on an empty cluster. 

Because of my our limited knowledge, could someone kindly confirm that EC2 instances should already be setup in the cluster to handle the tasks?

**Comment by brendanmcfarland** [comment]
Hey @hypertd - yep you've got it. ecs-watchbot will attempt to place containers on a cluster; with the assumption that the compute capacity (ec2s) is in place. We typically use autoscaling groups or spotfleets to manage and scale the underlying capacity on the cluster.
