### ISSUE TITLE
Audit + update ECS ARN format

### ISSUE THREAD

**Issue by vsmart** [mapbox/ecs-watchbot#320]
In preparation for the new ECS ARN format, we're going to audit this repo for any usage of the old ARN format. As a reminder, this is how they are changing:

ECS Service:
```
Old: arn:aws:ecs:region:account-id:service/service-name
New: arn:aws:ecs:region:account-id:service/cluster-name/service-name
```
ECS Task:
```
Old: arn:aws:ecs:region:account-id:task/task-id
New: arn:aws:ecs:region:account-id:task/cluster-name/task-id
```
ECS Container Instance:
```
Old: arn:aws:ecs:region:account-id:container-instance/id
New: arn:aws:ecs:region:account-id:container-instance/cluster-name/id
```
Change in ID format:

Old (36-characters): 1abf0f6d-a411-4033-b8eb-a4eed3ad252a
New (32-characters): 1abf0f6da4114033b8eba4eed3ad252a
Next actions:

- [x] Check cloudformation template for any arn hardcoding/parsing
- [x] Check lambda code for any ARN hardcoding/parsing
- [x] Check unit tests for ARN strings

cc @taraadiseshan

**Comment by jjanczyszyn** [comment]
I performed a couple of searches and didn't find anything that requires changes in preparation for the new ECS ARN format.

![Screen Shot 2019-12-04 at 09 40 16](https://user-images.githubusercontent.com/4153982/70166804-4bb20300-167a-11ea-9831-16a687a3a749.png)
