### ISSUE TITLE
Node 10 support

### ISSUE THREAD

**Issue by hcourt** [mapbox/ecs-watchbot#324]
Node 8 is EOL on 12/31/2019.
The stacks created by this repository are running on Node 8 and should be upgraded to Node 10.

ScalingLambda:
https://github.com/mapbox/ecs-watchbot/blob/f07922224b243539deb1cdb62463fe42c74e17eb/lib/template.js#L833

TotalMessagesLambda:
https://github.com/mapbox/ecs-watchbot/blob/f07922224b243539deb1cdb62463fe42c74e17eb/lib/template.js#L881

**Comment by mapsam** [comment]
@hcourt this is a good catch! I'm curious, with the code freeze starting on 12/16 and the node8 lambdas EOL coming up, are teams using ecs-watchbot expected to get their stacks updated this week?

If not - is it acceptable risk to wait to update stacks until after January 6th? (giving us one month to make updates to functions before the "no update" date on February 3rd)?

**Comment by hcourt** [comment]
@mapsam  Good question!

I think for teams that the code freeze applies to, they should be able to get approval if they need it.  If I'm able to merge this today, then this week would be obviously a much better time than next week to make the change.

January 6th is the date after which AWS will disable creating Lambdas with Node 8 runtimes.  The risk here is obviously if your Lambda is accidentally deleted.  If your team does not wish to go through the CM process during the freeze, then I would advise updating your staging stacks to Node10 in preparation for the update after the freeze.  This way you can be sure to have the change ready and on master.
