### ISSUE TITLE
Deploying sets desired capacity / running capacity back to 1

### ISSUE THREAD

**Issue by jseppi** [mapbox/ecs-watchbot#349]
I had a running watchbot service that had scaled up to 5 (the value of `maxSize` I had set in my template).
I increased `maxSize` to 10 and redeployed. The service desired and running capacity were reset to 1.

**Comment by rclark** [comment]
https://github.com/mapbox/ecs-watchbot/blob/f307ce694df75d851b2a83e8860b821db643b572/lib/template.js#L400-L404

Recently, the `DesiredCount` became an optional property in an `AWS::ECS::Service`. Having it present in the CloudFormation template is what causes stack updates to reset running container counts. 

Removing this property entirely ought to solve this issue.

**Comment by jseppi** [comment]
I think this is the same as #273
