### ISSUE TITLE
Dashboard: "WatchbotService: RunningCapacity, DesiredCapacity" chart is empty

### ISSUE THREAD

**Issue by jseppi** [mapbox/ecs-watchbot#351]
Potentially relevant details:
- using `capacity: 'FARGATE_SPOT'`

![image](https://user-images.githubusercontent.com/697848/105445543-7324b000-5c2d-11eb-9e51-23168e69a248.png)

**Comment by jseppi** [comment]
In CloudWatch metrics, I can find the `DesiredTaskCount` and `RunningTaskCount` service from the `ECS/ContainerInsights` namespace. Perhaps the dashboard should use those metrics for this chart?

![image](https://user-images.githubusercontent.com/697848/105446816-242c4a00-5c30-11eb-8e24-2e30897fbb00.png)

**Comment by rclark** [comment]
Yeah, this is a bug.

https://github.com/mapbox/ecs-watchbot/blob/f307ce694df75d851b2a83e8860b821db643b572/lib/dashboard.js#L141

https://github.com/mapbox/ecs-watchbot/blob/f307ce694df75d851b2a83e8860b821db643b572/lib/dashboard.js#L159

These rely on a custom Mapbox metric namespace that (a) never should have been in here in the first place and (b) no longer exists. Switching to the container insights metrics is the right move.
