### ISSUE TITLE
Bug in logging

### ISSUE THREAD

**Issue by rclark** [mapbox/ecs-watchbot#36]
It looks like [logs.js](https://github.com/mapbox/ecs-watchbot/blob/4e11dcc99bc8c419da026d29fc9fcca410f6b3ca/lib/logs.js#L49-L56) exposes a bug -- if a single log line is more than 50kb, its possible that you'll fall into the `else` condition and

```js
var drop = writable.buffer.shift();
```

`drop` could be undefined, leading to an uncaught exception when

```js
writable.buffer.current -= drop.length;
```

cc @jacquestardie

**Comment by emilymdubois** [comment]
> if a single log line is more than 50kb

@rclark, what would the expected behavior be here for the returned event? Parse the log line down from the beginning until it's under 50kb?

**Comment by emilymdubois** [comment]
Closed via https://github.com/mapbox/ecs-watchbot/pull/70
