### ISSUE TITLE
[Question] How to view metrics on worker tasks?

### ISSUE THREAD

**Issue by jakepruitt** [mapbox/ecs-watchbot#43]
Tried to find out how many desired/running worker tasks there were in my cluster today but I couldn't find the metrics. I could see the metrics for the Watcher service, but nothing was coming up for the Workers. Is there a way to register the workers as a service on the container? Alternatively, could we create custom cloudwatch metrics for keeping track of the number of worker tasks?

cc/ @rclark @yhahn

**Comment by jakepruitt** [comment]
After looking into it, I think the only thing we might be able to do is add a cron (or cron-ish job) to the Watcher task to call [listTasks](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/ECS.html#listTasks-property) for all of the `RUNNING`, `PENDING` and `STOPPED` Worker family tasks. This would then get sent to a custom cloudwatch metric of some sort (?). Typically, this metric would be recorded by a service, but I don't think it's feasible to put the workers in a service.

In terms of getting per-task metrics, this looks just about impossible do derive from existing cloudwatch metrics (even the per-service metrics are aggregated and don't give per-task min/max numbers, just average utilized of the reserved for the service). Our only two chances would be to add something to the tasks to write custom cloudwatch metrics themselves (yuck) or add a custom metric to cluster instances that uses [`docker stats`](https://docs.docker.com/engine/reference/commandline/stats/) (some prior art [here](https://github.com/mapbox/cwput/pull/21)).

**Comment by rclark** [comment]
ECS collects metrics for services, but not for individual tasks. The watcher uses a service to maintain the number of watcher's you've asked for, but each watcher runs workers by making RunTask requests -- these are not part of a service. As a result there are no metrics collected by ECS that aggregate or count anything about your workers.

I think that a good first step would be to adjust the [startedBy task attribute](https://github.com/mapbox/ecs-watchbot/blob/master/lib/tasks.js#L44) to something that is service-specific.

**Comment by rclark** [comment]
`docker stats` o_o this is great to know about.

Also learned that you can jump onto your cluster EC2s and [make http requests to the docker daemon](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.21/#/inspect-a-container) to learn quite a bit about what containers are doing

```
curl --unix-socket /var/run/docker.sock http:/containers/4a79a37e96b5/top
curl --unix-socket /var/run/docker.sock http:/containers/4a79a37e96b5/stats
```

**Comment by rclark** [comment]
As a note to self, you can get at these data from the docker API using ssh:

```
ssh ec2-12-34-5-67.compute-1.amazonaws.com "sudo curl -s --unix-socket /var/run/docker.sock http:/containers/json"
```

Might be helpful in the context of some kind of CLI tool for spot checking container utilization.

**Comment by rclark** [comment]
Closing because we have no clear action here.
