### ISSUE TITLE
describeContainerInstances limited to 100 at a time

### ISSUE THREAD

**Issue by rclark** [mapbox/ecs-watchbot#62]
The request to [describeContainerInstances here](https://github.com/mapbox/ecs-watchbot/blob/5f63c78e91b2863af00ab6e44e05e73fbeb6c671/lib/resources.js#L46) will fail on a cluster with more than 100 instances.

**Comment by emilymdubois** [comment]
Closed via https://github.com/mapbox/ecs-watchbot/pull/73
