### ISSUE TITLE
Extract progress tacking to its own repo

### ISSUE THREAD

**Issue by rclark** [mapbox/ecs-watchbot#71]
Let's pull the `watchbot-progress` functionality (lib/progress.js, bin/watchbot-progress.js, and tests) out into a standalone library. It could be useful in other scenarios and could use its own issue tracker.

cc @emilymdubois @GretaCB

**Comment by GretaCB** [comment]
Happy to help if needed (after I get uploads API work ready to go)!

**Comment by rclark** [comment]
@emilymdubois did this!
