### ISSUE TITLE
truncate stackname when calling runtask

### ISSUE THREAD

**Issue by mick** [mapbox/ecs-watchbot#78]
`task did not run: startedBy longer than 36.`

if stack has a long name, it will hit the limit of startedBy in the runtask api.  This seems safe to just truncate if that is the case

**Comment by emilymdubois** [comment]
@rclark looks like this may have been tackled in https://github.com/mapbox/ecs-watchbot/pull/85.

**Comment by rclark** [comment]
Hurray!
