### ISSUE TITLE
Remove cluster resource availability polling

### ISSUE THREAD

**Issue by rclark** [mapbox/ecs-watchbot#79]
[This section of the main loop](https://github.com/mapbox/ecs-watchbot/blob/bac01e7e261d0159b4ec580482c0e8e034e6599b/lib/main.js#L121-L133) checks the cluster's available resources in an attempt to avoid trying to launch a worker task when the cluster does not have sufficient resources. The primary motivation for adding this is that it helps avoid alarm-spam if the cluster is out of resources but messages need to be processed. Each attempt to launch a container that failed would lead to an alarm.

I think this concept needs to be revisited for a few reasons:
- #76 could provide a better alternative to the 1:1 alarms that motivated this in the first place
- An ECS cluster might want to keep track of the number of tasks that wanted to be placed but couldn't find sufficient resources. This could be used as a metric by which to add scale up the cluster's capacity.
- Doing this polling adds [almost 100 lines of code to test and maintain](https://github.com/mapbox/ecs-watchbot/blob/bac01e7e261d0159b4ec580482c0e8e034e6599b/lib/resources.js), and provides a pretty vague benefit.
- The polling results in the need to routinely list all the EC2s in the cluster. We could avoid making these API calls and it would have some impact on overall API request rate throttling that we've seen under some situations.

**Comment by jakepruitt** [comment]
We're thinking doing this would resolve a few issues we've seen with hanging watchers. Going to grab this and sketch it out, along with #76.
