### ISSUE TITLE
Error polling cluster resources: instanceIds can have at most 100 items.

### ISSUE THREAD

**Issue by emilymcafee** [mapbox/ecs-watchbot#81]
Looks like this condition can be hit when there are more than 100 container instances in a cluster.

cc @rclark @emilymdubois

**Comment by emilymdubois** [comment]
@emilymcafee, I think this may be the same issue as https://github.com/mapbox/ecs-watchbot/issues/62. Hopefully upgrading to v1.0.4 fixes the issue!

**Comment by emilymcafee** [comment]
🙇  upgrade fixed it. apologies for not doing my homework here.
