### ISSUE TITLE
throw on invalid template permissions?

### ISSUE THREAD

**Issue by sbma44** [mapbox/ecs-watchbot#87]
Got burned yesterday while porting an existing CloudFormation template that had wrapped some worker permissions in `PolicyDocument`s. `ecs-watchbot` rewrapped these in yet another `PolicyDocument`, which resulted in failure when launching the stack. Alas the error message was not particularly descriptive, and the generated template passed `aws cloudformation validate-template` without trouble.

I'd like to include a check in `ecs-watchbot` that checks for `PolicyDocument` entries in template permissions and throws a descriptive error if found. @rclark do you think this would be appropriate to include? If so I will make a quick PR.

**Comment by rclark** [comment]
> I'd like to include a check in ecs-watchbot that checks for PolicyDocument entries in template permissions and throws a descriptive error if found.

The fact that cloudformation's validation doesn't really help with IAM policy documents, and error messages are non-specific, is the real problem here. I'd be curious what you're imagining validation would look like, and whether that effort would be a good one to iron into cfn-config or cloudfriend instead of watchbot.

One the watchbot side, could documentation be improved at all? To indicate that you should be providing the `Statement`s from a policy document, and not the document itself?

**Comment by sbma44** [comment]
I was imagining a one-off check for the propery on `.some` of the array members passed on the `permissions` key. I agree that template validation is the real villain here, and that adding a bunch of nudges to ecs-watchbot is potentially ugly. However, insofar as ecs-watchbot is where the structure of the watcher/worker template lives, and that structure is what determines the invalidity of `PolicyDocument`s in this case, it seems like that would be a better home for an automated check than those other repos.

I would be happy to amend the docs as an alternative, though, if you don't want this repo to go down the path of many gentle nudges.

**Comment by rclark** [comment]
I'd rather not bite this off here in ecs-watchbot -- we'd be building a function that suggests it performs some level of template validation (or you could even just think of it as `watchbot.template()` input validation), but it would only be checking _one little piece of syntax_. 

Let's amend the docs first and hope that someday AWS offers an IAM policy syntax validator.

**Comment by sbma44** [comment]
Cool. PRed a README change -- merge if it looks ok to you?

**Comment by sbma44** [comment]
PR merged
